const defaultCards = [
    { "word": "Ability", "translation": "Способность, умение", "example": "She has the ability to solve complex problems." },
    { "word": "Accept", "translation": "Принимать", "example": "I accept your apology." },
    { "word": "Access", "translation": "Доступ", "example": "We need internet access to work." },
    { "word": "Accomplish", "translation": "Выполнять, достигать", "example": "We have a lot to accomplish today." },
    { "word": "Account", "translation": "Счет, аккаунт", "example": "Please log in to your account." },
    { "word": "Achieve", "translation": "Достигать", "example": "He worked hard to achieve his goals." },
    { "word": "Action", "translation": "Действие", "example": "It's time to take action." },
    { "word": "Actually", "translation": "На самом деле, вообще-то", "example": "I actually like this design." },
    { "word": "Add", "translation": "Добавлять", "example": "Click here to add a new item." },
    { "word": "Advantage", "translation": "Преимущество", "example": "This framework has a big advantage." },
    { "word": "Advice", "translation": "Совет", "example": "Can you give me some advice?" },
    { "word": "Affect", "translation": "Влиять", "example": "The weather will affect our plans." },
    { "word": "Agree", "translation": "Соглашаться", "example": "I agree with your opinion." },
    { "word": "Allow", "translation": "Позволять, разрешать", "example": "The system allows you to upload files." },
    { "word": "Already", "translation": "Уже", "example": "I have already finished the layout." },
    { "word": "Although", "translation": "Хотя", "example": "Although it was raining, we went for a walk." },
    { "word": "Always", "translation": "Всегда", "example": "I always test my code." },
    { "word": "Amount", "translation": "Количество", "example": "A large amount of data was lost." },
    { "word": "Analyze", "translation": "Анализировать", "example": "We need to analyze the results." },
    { "word": "Answer", "translation": "Ответ, отвечать", "example": "I don't know the answer." },
    { "word": "Application", "translation": "Приложение", "example": "This is a single-page application." },
    { "word": "Approach", "translation": "Подход", "example": "We need a new approach to this problem." },
    { "word": "Argue", "translation": "Спорить", "example": "They argue about the best programming language." },
    { "word": "Array", "translation": "Массив", "example": "Save these elements in an array." },
    { "word": "Assume", "translation": "Предполагать", "example": "I assume everything is working." },
    { "word": "Attempt", "translation": "Попытка, пытаться", "example": "This is my second attempt." },
    { "word": "Attention", "translation": "Внимание", "example": "Pay attention to the details." },
    { "word": "Avoid", "translation": "Избегать", "example": "Try to avoid using inline styles." },
    { "word": "Background", "translation": "Фон", "example": "The background color should be dark." },
    { "word": "Balance", "translation": "Баланс", "example": "Keep a balance between work and rest." },
    { "word": "Behavior", "translation": "Поведение", "example": "The script changes the behavior of the button." },
    { "word": "Benefit", "translation": "Выгода, польза", "example": "What is the benefit of this library?" },
    { "word": "Bottom", "translation": "Низ, нижняя часть", "example": "Scroll to the bottom of the page." },
    { "word": "Branch", "translation": "Ветка (в Git), филиал", "example": "Create a new branch for your feature." },
    { "word": "Button", "translation": "Кнопка", "example": "Click the submit button." },
    { "word": "Cancel", "translation": "Отменить", "example": "You can cancel the operation." },
    { "word": "Capture", "translation": "Захват, захватывать", "example": "We need to capture the network traffic." },
    { "word": "Cause", "translation": "Причина, вызывать", "example": "What was the cause of the bug?" },
    { "word": "Certain", "translation": "Определенный, уверенный", "example": "I am certain about this decision." },
    { "word": "Challenge", "translation": "Вызов, сложная задача", "example": "Learning to code is a challenge." },
    { "word": "Change", "translation": "Изменение, менять", "example": "Don't change the main structure." },
    { "word": "Choose", "translation": "Выбирать", "example": "Choose the right tool for the job." },
    { "word": "Clear", "translation": "Ясный, очищать", "example": "The instructions are very clear." },
    { "word": "Client", "translation": "Клиент", "example": "The client requested a new feature." },
    { "word": "Code", "translation": "Код", "example": "Clean code is easy to read." },
    { "word": "Common", "translation": "Общий, распространенный", "example": "This is a common mistake." },
    { "word": "Compare", "translation": "Сравнивать", "example": "Let's compare these two options." },
    { "word": "Complete", "translation": "Завершать, полный", "example": "I will complete the task tomorrow." },
    { "word": "Complex", "translation": "Сложный", "example": "The logic is too complex." },
    { "word": "Condition", "translation": "Условие", "example": "Check the condition before proceeding." },
    { "word": "Confirm", "translation": "Подтверждать", "example": "Please confirm your email address." },
    { "word": "Connect", "translation": "Подключать", "example": "Connect to the database." },
    { "word": "Consider", "translation": "Рассматривать, учитывать", "example": "Consider all edge cases." },
    { "word": "Content", "translation": "Содержимое, контент", "example": "The main content is on the right." },
    { "word": "Continue", "translation": "Продолжать", "example": "Click to continue." },
    { "word": "Control", "translation": "Контроль, управлять", "example": "You have full control over the layout." },
    { "word": "Create", "translation": "Создавать", "example": "Create a new file in the folder." },
    { "word": "Current", "translation": "Текущий", "example": "What is your current progress?" },
    { "word": "Data", "translation": "Данные", "example": "Save the data in JSON format." },
    { "word": "Database", "translation": "База данных", "example": "The database connection failed." },
    { "word": "Decide", "translation": "Решать", "example": "We need to decide quickly." },
    { "word": "Default", "translation": "По умолчанию", "example": "Use the default settings." },
    { "word": "Define", "translation": "Определять", "example": "Define the variable clearly." },
    { "word": "Delete", "translation": "Удалять", "example": "Do not delete this folder." },
    { "word": "Depend", "translation": "Зависеть", "example": "It depends on the user's choice." },
    { "word": "Design", "translation": "Дизайн, проектировать", "example": "Minimalist design is very popular." },
    { "word": "Detail", "translation": "Деталь", "example": "Pay attention to every detail." },
    { "word": "Develop", "translation": "Разрабатывать", "example": "I develop simple web applications." },
    { "word": "Device", "translation": "Устройство", "example": "Test the site on a mobile device." },
    { "word": "Difference", "translation": "Разница", "example": "What is the difference between HTML and CSS?" },
    { "word": "Difficult", "translation": "Сложный", "example": "This bug is difficult to fix." },
    { "word": "Directory", "translation": "Каталог, директория", "example": "Save the file in the root directory." },
    { "word": "Discover", "translation": "Обнаруживать", "example": "I discovered a new tool today." },
    { "word": "Display", "translation": "Отображать, дисплей", "example": "The image doesn't display correctly." },
    { "word": "Download", "translation": "Скачивать", "example": "You can download the template here." },
    { "word": "Effect", "translation": "Эффект, влияние", "example": "Hover effect makes the button interactive." },
    { "word": "Effort", "translation": "Усилие", "example": "It takes effort to learn programming." },
    { "word": "Empty", "translation": "Пустой", "example": "The array is currently empty." },
    { "word": "Enable", "translation": "Включать, активировать", "example": "Enable the dark mode." },
    { "word": "Ensure", "translation": "Обеспечивать, убеждаться", "example": "Ensure all files are saved." },
    { "word": "Environment", "translation": "Среда, окружение", "example": "Set up your development environment." },
    { "word": "Error", "translation": "Ошибка", "example": "A syntax error occurred." },
    { "word": "Event", "translation": "Событие", "example": "Add a click event listener." },
    { "word": "Exactly", "translation": "Точно, именно", "example": "That is exactly what I need." },
    { "word": "Example", "translation": "Пример", "example": "Can you give me an example?" },
    { "word": "Execute", "translation": "Выполнять", "example": "Execute the script in the terminal." },
    { "word": "Expect", "translation": "Ожидать", "example": "I expect the project to be done soon." },
    { "word": "Experience", "translation": "Опыт", "example": "He has good experience in frontend." },
    { "word": "Explain", "translation": "Объяснять", "example": "Please explain how this works." },
    { "word": "Feature", "translation": "Особенность, функция", "example": "This is a new feature of the app." },
    { "word": "File", "translation": "Файл", "example": "Open the JavaScript file." },
    { "word": "Find", "translation": "Находить", "example": "I need to find a solution." },
    { "word": "Focus", "translation": "Фокус, сосредотачиваться", "example": "Focus on the main logic." },
    { "word": "Folder", "translation": "Папка", "example": "Put all images in one folder." },
    { "word": "Follow", "translation": "Следовать", "example": "Follow the instructions carefully." },
    { "word": "Force", "translation": "Заставлять, сила", "example": "Use this command to force the update." },
    { "word": "Form", "translation": "Форма", "example": "Fill out the contact form." },
    { "word": "Format", "translation": "Формат", "example": "The file must be in JSON format." },
    { "word": "Front", "translation": "Передняя часть", "example": "This is the front of the card." },
    { "word": "Function", "translation": "Функция", "example": "Call the function to update the screen." }
];